package gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

public class EditServiceController {
	@FXML
	private Label lbCodeService;
	@FXML
	private TextField tfCodeService;
	@FXML
	private Label lbNameOfService;
	@FXML
	private Label lbPhone;
	@FXML
	private TextField tfPhone;
	@FXML
	private Label lbDescription;
	@FXML
	private TextField tfDescription;
	@FXML
	private Label lbCostoBase;
	@FXML
	private TextField tfCostoBase;
	@FXML
	private Button btnEditService;
	@FXML
	private Button btnCancel;
	@FXML
	private ComboBox cbxNameOfService;
	@FXML
	private Label lbEstimatedTime;
	@FXML
	private TextField tfEstimatedTime;

	// Event Listener on Button[#btnEditService].onAction
	@FXML
	public void EditService(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancel].onAction
	@FXML
	public void Cancel(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#cbxNameOfService].onAction
	@FXML
	public void ChooseTheService(ActionEvent event) {
		// TODO Autogenerated
	}
}
