package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

public class CreateVehicleController {
	@FXML
	private Label lbPlate;
	@FXML
	private TextField tfPlate;
	@FXML
	private Label lbBrand;
	@FXML
	private TextField tfBrand;
	@FXML
	private Label lbModel;
	@FXML
	private TextField tfModel;
	@FXML
	private Label lbYear;
	@FXML
	private TextField tfYear;
	@FXML
	private Label lbFuelType;
	@FXML
	private Button btnVehicle;
	@FXML
	private Button btnCancel;
	@FXML
	private ComboBox cbxTypeFuel;
	@FXML
	private Label lbOwner;
	@FXML
	private ComboBox cbxOwner;

	// Event Listener on Button[#btnVehicle].onAction
	@FXML
	public void SaveVehicle(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancel].onAction
	@FXML
	public void Cancel(ActionEvent event) {
		// TODO Autogenerated
	}
}
