package business;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

public class EditServiceController {
	@FXML
	private Label lbCodeService;
	@FXML
	private TextField tfCodeService;
	@FXML
	private Label lbNameOfService;
	@FXML
	private Label lbPhone;
	@FXML
	private TextField tfPhone;
	@FXML
	private Label lbDescription;
	@FXML
	private TextField tfDescription;
	@FXML
	private Label lbCostoBase;
	@FXML
	private TextField tfCostoBase;
	@FXML
	private Button btnEditService;
	@FXML
	private Button btnCancel;
	@FXML
	private ComboBox cbxNameOfService;
	@FXML
	private Label lbEstimatedTime;
	@FXML
	private TextField tfEstimatedTime;

	public void initialize() {
		cbxNameOfService.getItems().addAll("","mecánica general", "frenos", "electricidad", "motor");
	}


	private boolean validForm() {
		String message = "";

		
		if (this.tfCodeService.getText().trim().isEmpty()) {
			tfCodeService.setStyle("-fx-border-color:red; -fx-border-width:2;");
			message += "Código de servicio vacío \n";
		} else {
			tfCodeService.setStyle("");
		}

		
		if (cbxNameOfService.getValue() == null) {
			cbxNameOfService.setStyle("-fx-border-color:red; -fx-border-width:2;");
			message += "Nombre del servicio no seleccionado \n";
		} else {
			cbxNameOfService.setStyle("");
		}

		
		if (this.tfPhone.getText().trim().isEmpty()) {
			tfPhone.setStyle("-fx-border-color:red; -fx-border-width:2;");
			message += "Número de teléfono vacío \n";
		} else {
			try {
				Integer.parseInt(tfPhone.getText().trim());
				tfPhone.setStyle("");
			} catch (NumberFormatException e) {
				message += "El teléfono debe ser numérico \n";
				tfPhone.setStyle("-fx-border-color:red; -fx-border-width:2;");
			}
		}

		
		if (this.tfDescription.getText().trim().isEmpty()) {
			tfDescription.setStyle("-fx-border-color:red; -fx-border-width:2;");
			message += "Descripción vacía \n";
		} else {
			tfDescription.setStyle("");
		}

		
		if (this.tfCostoBase.getText().trim().isEmpty()) {
			tfCostoBase.setStyle("-fx-border-color:red; -fx-border-width:2;");
			message += "Costo base vacío \n";
		} else {
			try {
				Double.parseDouble(tfCostoBase.getText().trim());
				tfCostoBase.setStyle("");
			} catch (NumberFormatException e) {
				message += "El costo base debe ser un número válido \n";
				tfCostoBase.setStyle("-fx-border-color:red; -fx-border-width:2;");
			}
		}

		
		if (this.tfEstimatedTime.getText().trim().isEmpty()) {
			tfEstimatedTime.setStyle("-fx-border-color:red; -fx-border-width:2;");
			message += "Tiempo estimado vacío \n";
		} else {
			try {
				Integer.parseInt(tfEstimatedTime.getText().trim());
				tfEstimatedTime.setStyle("");
			} catch (NumberFormatException e) {
				message += "El tiempo estimado debe ser un número entero \n";
				tfEstimatedTime.setStyle("-fx-border-color:red; -fx-border-width:2;");
			}
		}

		
		if (!message.isEmpty()) {
			Alert alert = new Alert(AlertType.INFORMATION);
			alert.setHeaderText("Campos Faltantes o Inválidos");
			alert.setTitle("Ups!");
			alert.setContentText(message);
			alert.show();
		}

		return message.isEmpty();
	}

	// Event Listener on Button[#bthSave].onAction
	@FXML
	public void SaveClient(ActionEvent event) {
		if (validForm()) {
			
			System.out.println("Servicio validado correctamente.");
		}
	}
	
	// Event Listener on Button[#btnCancel].onAction
	@FXML
	public void Cancel(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/gui/GUIMantenimientoDeClientes.fxml"));
			Parent root = loader.load();
			Scene scene = btnCancel.getScene();
			scene.setRoot(root);
			scene.getWindow().sizeToScene();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	// Event Listener on ComboBox[#cbxNameOfService].onAction
	@FXML
	public void ChooseTheService(ActionEvent event) {
		// TODO Autogenerated
	}
}
