package business;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;

import javafx.scene.input.KeyEvent;

public class GUIMantenimientoDeOrdenesController {
	@FXML
	private Button btnRegisterOrder;
	@FXML
	private Button btnEditOrder;
	@FXML
	private Button btndeleteOrder;
	@FXML
	private TextField tfSearch;
	@FXML
	private Button btnSearch;
	@FXML
	private Button btnCancelar;

	// Event Listener on Button[#btnRegisterOrder].onAction
	@FXML
	public void RegisterOrder(ActionEvent event) {
		loadView("/gui/CreateOrders.fxml", btnRegisterOrder);
	}
	// Event Listener on Button[#btnEditOrder].onAction
	@FXML
	public void EditOrder(ActionEvent event) {
		loadView("/gui/EditOrders.fxml", btnEditOrder);
	}
	// Event Listener on Button[#btndeleteOrder].onAction
	@FXML
	public void DeleteOrder(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TableView.onMouseClicked
	@FXML
	public void Delete(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#tfSearch].onKeyReleased
	@FXML
	public void SearchForAll(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSearch].onAction
	@FXML
	public void Search(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void GoToIndex(ActionEvent event) {
		loadView("/gui/MenuGeneral.fxml", btnCancelar);
	}
	
	private void loadView(String fxmlPath, Button triggerButton) {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource(fxmlPath));
            Parent root = loader.load();
            Scene scene = triggerButton.getScene();
            scene.setRoot(root);
            scene.getWindow().sizeToScene();
            scene.getWindow().centerOnScreen();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
