package business;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.input.KeyEvent;
import javafx.scene.input.MouseEvent;
import javafx.event.ActionEvent;
import javafx.stage.Stage;
import java.io.IOException;

public class GUIMantenimientoDeClientesController {
	@FXML
	private Button btnNewClient;
	@FXML
	private Button btnEditClient;
	@FXML
	private Button btnDeleteClient;
	@FXML
	private TextField tfSearch;
	@FXML
	private Button btnSearch;
	@FXML
	private Button btnCancelar;
	
	// Event Listener on Button[#btnNewClient].onAction
	@FXML
	public void CreateClient(ActionEvent event) {
		loadView("/gui/CreateClient.fxml", btnNewClient);
	}
	// Event Listener on Button[#btnEditClient].onAction
	@FXML
	public void EditClient(ActionEvent event) {
		loadView("/gui/EditClient.fxml", btnEditClient);
	}
	// Event Listener on Button[#btnDeleteClient].onAction
	@FXML
	public void DeleteClient(ActionEvent event) {
		
	}
	// Event Listener on TableView.onMouseClicked
	@FXML
	public void Delete(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#tfSearch].onKeyReleased
	@FXML
	public void ViewTheOptions(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSearch].onAction
	@FXML
	public void Search(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
    public void GoToIndex(ActionEvent event) {
		loadView("/gui/MenuGeneral.fxml", btnCancelar);
    }
    
	private void loadView(String fxmlPath, Button triggerButton) {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource(fxmlPath));
            Parent root = loader.load();
            Scene scene = triggerButton.getScene();
            scene.setRoot(root);
            scene.getWindow().sizeToScene();
            scene.getWindow().centerOnScreen();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
