package business;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;

import javafx.scene.input.KeyEvent;

public class GUIMantenimientoDeServiciosController {
	@FXML
	private Button btnNewService;
	@FXML
	private Button btnEditService;
	@FXML
	private Button btnDeleteService;
	@FXML
	private TextField tfSearch;
	@FXML
	private Button btnSearch;
	@FXML
	private Button btnCancelar;

	// Event Listener on Button[#btnNewService].onAction
	@FXML
	public void CreateService(ActionEvent event) {
		loadView("/gui/CreateService.fxml", btnNewService);
	}
	// Event Listener on Button[#btnEditService].onAction
	@FXML
	public void EditService(ActionEvent event) {
		loadView("/gui/EditService.fxml", btnEditService);
	}
	// Event Listener on Button[#btnDeleteService].onAction
	@FXML
	public void DeleteService(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TableView.onMouseClicked
	@FXML
	public void Delete(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#tfSearch].onKeyReleased
	@FXML
	public void ViewTheOptions(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSearch].onAction
	@FXML
	public void Search(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void GoToIndex(ActionEvent event) {
		loadView("/gui/MenuGeneral.fxml", btnCancelar);
	}

	private void loadView(String fxmlPath, Button triggerButton) {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource(fxmlPath));
            Parent root = loader.load();
            Scene scene = triggerButton.getScene();
            scene.setRoot(root);
            scene.getWindow().sizeToScene();
            scene.getWindow().centerOnScreen();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
